### ISSUE TITLE
does not like spaces in the path

### ISSUE THREAD

**Issue by kdschlosser** [kiyolee/openssl1_1-win-build#1]
I want to say that this is going to be a life saver if I get it running... I am going to utilize the build setup that you have and port it to python this way I can compile the thing without the need for VS, just need Visual Studio Build Tools. 

It does not like spaces in the path to any of the files. so "New Folder" as a name for the parent folder to hold the repos does not work...

as a side note.. nasm (nasm2) can be gotten from nuget

for my project I will be able to download a portable vbersion of perl and then i can download a cli version of nuget from 
https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
 and use this command to download it.

nuget install nasm2 -Version 2.13.3.1

Now I had perl and also nuget in my path but this did not work. it was unable to locate them.. I had to change the VSD variables to the full path.. not sure why that is...

In order to fix the issue with the spaces.

This..
```
mkdir $(OutDir)_work 2&gt;nul\
mkdir $(OutDir)_work\static 2&gt;nul\
$(PERL) %(FullPath) nasm $(OutDir)_work\static\%(Filename).asm &amp;&amp; $(NASM) -f win64 -DNEAR -Ox -g -o $(IntDir)%(Filename).obj $(OutDir)_work\static\%(Filename).asm
```

would become
```
mkdir &quot;$(OutDir)_work&quot; 2&gt;nul
mkdir &quot;$(OutDir)_work\static&quot; 2&gt;nul
$(PERL) &quot;%(FullPath)&quot; nasm &quot;$(OutDir)_work\static\%(Filename).asm&quot; &amp;&amp; $(NASM) -f win64 -DNEAR -Ox -g -o &quot;$(IntDir)%(Filename).obj&quot; &quot;$(OutDir)_work\static\%(Filename).asm&quot;
```

I do have a question regarding this..
is this
```
$(PERL) &quot;%(FullPath)&quot; nasm &quot;$(OutDir)_work\static\%(Filename).asm&quot; &amp;&amp; $(NASM) -f win64 -DNEAR -Ox -g -o &quot;$(IntDir)%(Filename).obj&quot; &quot;$(OutDir)_work\static\%(Filename).asm&quot;
```

2 commands???
```
$(PERL) &quot;%(FullPath)&quot; nasm &quot;$(OutDir)_work\static\%(Filename).asm&quot; 

$(NASM) -f win64 -DNEAR -Ox -g -o &quot;$(IntDir)%(Filename).obj&quot; &quot;$(OutDir)_work\static\%(Filename).asm&quot;
```

I don't remember MS_DOS syntax for chaining commands.. It has been over 20 years since I have had to use that syntax. I believe it is && I cannot remember tho. 

This is going to make my life a whole lot easier...

**Comment by kiyolee** [comment]
I do kind of aware the potential problem of spaces in file paths.
Given the potential messiness, I personally would avoid spaces in file paths for software development in general.
However, I do agree it is nice that can be fixed.
That will take a bit of time though. Please be patient.
Those are 2 commands. "&&" ensures the second command does not run if the first one fails.

**Comment by kiyolee** [comment]
Thanks for the advice of using nuget. Should learn more about that.

**Comment by kdschlosser** [comment]
I am well aware of using spaces in the paths when developing.. This is being compiled using VS and it should be able to use spaces.. I didn't put much thought to it. I just plopped a new folder on my desktop and away I went..

I just got it to compile. there were a few more issues I posted them for you.

**Comment by kiyolee** [comment]
Well, I am the kind of developers who always rename "New Folder" to something else without spaces.

**Comment by kdschlosser** [comment]
I didn't put much thought to it at the time.. I guess I was excited to come across this repo and missed doing that... LOL...
