### ISSUE TITLE
There are some problems with static build of openssl

### ISSUE THREAD

**Issue by lrh450330** [kiyolee/openssl1_1-win-build#11]
In the file libcrypto-1_1-static.vcxproj：

`   <ClCompile Include="..\..\crypto\sha\keccak1600.c">
      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">true</ExcludedFromBuild>
      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Release|x64'">true</ExcludedFromBuild>
    </ClCompile>
    <ClCompile Include="..\..\crypto\whrlpool\wp_block.c">
      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">true</ExcludedFromBuild>
      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Release|x64'">true</ExcludedFromBuild>
    </ClCompile>`

Compared with the content of Makefile, 64 bit system has no such limitation，this triggers a link error：Unresolved external symbol __imp__SHA3_absorb

**Comment by kiyolee** [comment]
Can you clarify? What are the 4 "true" words supposed to mean?

**Comment by lrh450330** [comment]
The problem code is not displayed properly. I have updated the display format.

**Comment by kiyolee** [comment]
no. the 2 files are x86 (32-bit) only. for 64-bit, there are corresponding assembly code.
the differences are intentional.

**Comment by lrh450330** [comment]
Maybe,my compilation option is no-asm

**Comment by kiyolee** [comment]
You shouldn't be using this if you just want to build it yourself. You may just use openssl official release.
