### ISSUE TITLE
Why is Release greater than Debug in build-VS2019

### ISSUE THREAD

**Issue by coolxv** [kiyolee/openssl1_1-win-build#13]
Debug:libcrypto-1_1-static.lib      15MB
Release:libcrypto-1_1-static.lib      124MB

**Comment by kiyolee** [comment]
Interesting, never noticed that before.
I don't have a definite answer.
I have checked that the individual object files that go into the lib file are much bigger to start with.
My guess is that this is a consequence of enabling LTO (Link time optimization/Whole program optimization), indeed only applied for Release build.
If I understand that correctly, for LTO to work, the object files need to contain some kind of intermediate codes for final conversion to assembly code upon/after LTO. Effectively, all object files with LTO contains some kind of digested form of original source codes. All the extra information for optimization can easily cause the object files to be much bigger.
