### ISSUE TITLE
VS properties ZLIB_INC_DIR incorrect path

### ISSUE THREAD

**Issue by kdschlosser** [kiyolee/openssl1_1-win-build#3]
I had to edit the property and remove the trailing `\` in order to have it work properly

**Comment by kiyolee** [comment]
Interesting, I can build all my VS solutions without any such problem.
Can you show me the errors you get?

**Comment by kiyolee** [comment]
Btw, the trailing '\' is there to follow VS common convention that directory variables (e.g. $(OutDir)) always have the trailing '\' so you don't need to write $(OutDir)\bar. I think it is like that since VS2010. VS2008 is different and may require to write something $(XxxDir)\bar. VS also complains for some directory settings if the trailing '\' is not there.

**Comment by kdschlosser** [comment]
if I have the trailing slash there even tho the variable is added to the extra include paths i get compile errors for not being able to locate zlib.h. once i remove the trailing slash.. the problem goes away.

**Comment by kdschlosser** [comment]
give me a few to revert the changes and to run the compile again

**Comment by kdschlosser** [comment]
blasted thing. It was kicking out an error at me every time i ran the thing before. the error was chained..
I believe it was openssl complaining that it could not find libcrypto. and libcrypto was complaining because it ws unable to import z_lib.h .. 

something along those lines. I added the slash back in and now everything is operating as it should..
each day I do hate Microsoft products just a tad more. always with the goofy behavior.

**Comment by kiyolee** [comment]
You don't happen to have an include path (env var INCLUDE or other VS settings) that picks up zlib/openssl from elsewhere?

**Comment by kdschlosser** [comment]
nope I do not set up any kind of an environment unless I have a specific need for one and that environment is only good for that windows/command prompt. 

I may have found the problem. in my path statement a few entries before the entries for perl and for nasm there was  double semicolon.. This was done by an application either on install or when it was removed.. you would think that VS knows how to handle this I would have to look at the vsvars script and see if it is written to break an iteration of the path statement when split on the semicolon if it finds a blank entry I will test it.. But I am almost sure that this would be the problem..


If memory serves there is not supposed to be a trailing semicolon at the end of the path statement if one was there and a program added to it it would make an empty entry.. This might stop path from being parsed all the way.. I have to test it..

Thank you for bringing that up which made me fully read the whole path line to check for something that should not be in there..

**Comment by kiyolee** [comment]
Interesting, double semicolons, never thought about that.

**Comment by kdschlosser** [comment]
me either. I still have to test it to see if it is going to work. I have to download your repo again I mucked the one up that i downloaded and do not remember what I was doing so i can't unmuck it. LOL
