### ISSUE TITLE
I hope you do not mind..

### ISSUE THREAD

**Issue by kdschlosser** [kiyolee/openssl1_1-win-build#5]
I was chatting with the folks over at OpenSSL and the windows build. coupled with the fact they they use nmake which is a horribly slow process. The idea was to speed this up in some fashion.. I saw that they used perl and suggested to them using perl to spawn multiple compiler processes instead of using nmake. 

sine I opened that discussion with them I then came across your reporitory.. Which I do want to say is one hell of a job...I do not know if you had any help or if you reverse engineered the OpenSSL build process and put together a way to accomplish it in VS still keeping the use of perl and nasm.. 

I brought up this project and provided a link to them. There is a specific reason as to why i did this.. First off... it is a smashing job..
Second. MSBuild has a nifty feature. you can tell it to spawn multiple compiler processes. This is going to make the build n times faster.. where n is the number of cores you have. MSBuild can also be invoked from the command line and will process VS solutions without the need to change a thing. so from the standpoint of using a CI this is a huge improvement. That is fantastic..

I told them to speak with you whether they will or will not is entirely up to them. The concern was OpenSSL 3.0 and the changes made to it and this project is not compatible with it.. And also because OpenSSL is included with this and is not a separate entity.

I have not tried this so I figured I would ask. Is the OpenSSL included with this project an unmodified version?

Also is it possible to add in the ability to download a portable version of perl and also have it add nasm whether by download or by using nuget?? having these things be automatic would turn this into a one click or a 1 command to compile design.. zlib would have to be added to the project and not be a standalone thing that needs to be done ahead of time. that should fairly simple to accomplish.

as far as the perl and the nasm go.. I cn see that there is the ability to carry out cli commands. a download can be acompilshed by powershell. pass a script to a call to the executable.

We can also use powershell to unzip perl into the project . then the user would not have to worry about setting any path statements...

I have a working script to handle the unzipping for powershell. It also includes the making/modification of an ini file for powershell that adds a line to point to .NET 3.5 or newer if= that exists on the system..that is where the zip API is.. this script can either be passed as a string to powershell or a script file can be included with the project and that filename would get passed instead.

Set this as the first thing to be carried out if they do not exist on the system.. This should be fairly easy stuff to add...

I suggested adding these solutions as a sub module with your permissions of course. IDK if it is even being considered. But I do want you to know what is going on if by chance someone does come asking...  If it is not something that you would be willing to do then tell them not interested.. I did not make any guarantees on your behalf I only suggested they should investigate and ask you  directly..

**Comment by kiyolee** [comment]
I pretty much reverse engineered the build process by reading the generated Makefile for nmake.
I have also built openssl manually for enough times to understand what the build process generates.
All these was done by myself with no input from anybody else.

For openssl 3.0 currently under development, I have also done a similar solution. If interested, see branch `win-build` of my openssl fork. That's less comprehensive and only supports VS2019 currently.

While build openssl my way has some advantages, it loses the flexiblity to support all the various configuration options available through the official build process. For instance, I decided not to include dynamic engine support. Some generated headers are also required to be kept here for VS to build. Those headers can be problematic for people simply use the official build process.

Pulling in perl/nasm automatically would be nice but no exact idea how to do that without being too complicated. I also personally don't like the idea that executables are downloaded and ran automatically. How can I be sure the downloaded executables are reliably secure.

Other than building, there is no other significant change to openssl itself. Simply git diff can tell you what I have changed. The changes are mostly to get around compiler errors somehow pops up in my way of building things. I do fix a bug for auto testing, that's some very odd characteristic about using static vc runtimes and I don't even think it is worthy for pull-request.

I have thought about to use git submodule to include zlib here. But I decided not to take that path yet. Similar to the perl/nasm requirements, I think that is better served by using some higher level build scripts. That also leaves the flexiblity for other people to use their own zlib builds, perhaps.

It'd be my honour if this can be incorporated into the official openssl project. But I do see that there are enough differences in the building process that this may not fit the goal of the official openssl project.

**Comment by kdschlosser** [comment]
I tip my hat to you for reverse engineering the whole thing. I had  started down that road to build a python based compiler that had no dependency on using nmake..

setting the file downloads up would be a snap.. You already execute commands when you call perl and also nasm. This same mechanism could be used to install the deps.

the perl would be a portable version downloaded from activestate so it would not be something that would need to be worried about.. that would need to be uncompreessed using the zip API built into windows so powershell would need to be executed to carry out that task.

I am sure there is a way to probably tell nuget to install nasm from inside of VS.. but if the user does not have nuget installed into vs that would be an issue. a cli version of nuget can be obtained from nuget. so there should be no concern about executing that either.. the cli version of nuget can be used to download nasm from nugets servers.. again same deal wouldn't have to worry about it... those deps would not be obtained from any kind of a source that could not be considered as a trusted source...
inform anyone of what the project is going to do right on the main page of the repo so nothing is being obtained without knowledge of the user.. in all actuality a single powershell script could be made  to handle the downloads and un zipping and also calling nuget to install nasm.. this sams script can be used to display a dialog that would prompt the user asking them if they wanted to download the files.

I believe that visual studio will kick back an error if an exit code is not a 0.. 

it should be fairly straight forward to do. the hardest part is the power shell script and setting it up so that it uses .net3.5 or higher in order to have access to the zip api.

**Comment by kdschlosser** [comment]
well would you look at that.... perl can be downloaded using nuget!

**Comment by kiyolee** [comment]
I may. Can't promise anything as being CI capable is not one of my goal for this project.
However, thanks for suggestions for how to make my offering more useful.
