### ISSUE TITLE
msbuild build customization

### ISSUE THREAD

**Issue by kdschlosser** [kiyolee/openssl1_1-win-build#7]
I am working on an msbuild customization that will be a better integration into calling perl to build the assembly files.

There already exists a build customization for masm.
This is going to allow for a more streamlined build instead of the current design where masm is a piggybacked onto perl. It is going to provide logging and also the ability to set command line options.

Using the build customization we have the ability to pass the assembly file that is created using perl to the masm build customization and that will compile the the assembly code into an object and that object will then get passed to the linker. 

The _work would no longer be needed. 
it is going to have a proper logging routing,
The best part.. it is going to automatically set everything up based on the .pl file extension. so when a file gets added it will populate the information in the properties for that file. They will be editable
It will provide most of the command line switches available for perl. You will also be able to add/change any command line arguments for the script (programfile)
There is going to be an outfile field that will have a default value in it but can be removed/updated

paths to perl and also nasm will no longer need to be set into the path statement by the user. perl and nasm can be supplied with the solutions, that could end up making for a really large repository. I am thinking simply instructing the user to use nuget to install perl and nasm is going to be fine. It will use the default paths for those and will be preset into the build system using a relitive path from the project.

I have a question regarding the use of perl... when doing a 64 bit build does a 64bit version of perl need to be used and same goes for x86. or does it not matter?

Also You  are more familiar with VS then I am. If you are willing would you mind having a look at this thing, I seem to be stuck with it. I am going to poke about it some more and see if I can get unstuck. but if not another set of eyes would be helpful. It's a pain because of how microsoft has these build components spread across 3 files. I also do not know all of the tags and what can and cannot be done using these damned files. You might know.

**Comment by kiyolee** [comment]
To my understanding, whether perl is 32 or 64 bit does not matter. The perl programs does not check that to behave differently. Same for nasm.

I don't quite fully understand what your masm customisation is about. I do notice there is some addon to VS to make masm available as a proper tool so you can set options in GUI like other tools (cl and link, etc.). But I think that is probably more complicated that simply download the tools and make them available through system path or edit tools.props.

One of my objectives here is also to follow the official build as close as possible. That makes following upcoming releases/changes easier.

Also notice that the _work directories are there so that batch builds can happen without interfering each other. Inside IDE, I used to batch builds all 4 combinations ((Debug,Release) x (Win32,x64)) at the same time. In that case, the same asm pl file for each platforms (Win32,x64) needs to generate 2 asm files in 2 difference places so 2 nasm/masm can run at the same time. If you are thinking of generating the asm file once to one location, batch builds are not going to work.

Batch builds are probably not useful for your project, but for myself to develop openssl apps, I do like both Debug/Release builds ready for use. This may be another weakness of VS that it can't sort out common compilation between batch builds. The 2 nasm/masm compilations (Debug,Release) per pl file per platforms are going to generate the same object. I would like to optimize that away but I can't find a simple way.

**Comment by kdschlosser** [comment]
I do not know if masm has any mechanism to output debugging info or not.. If it does then what I am doing is going to be the trick..

You can apply custom build tools to projects in VS. if you right click on the project and then click on `build dependencies  --- > build customization`

I do not know why they have the customization under the dependencies It doesn't really belong there.

anywho.. A dialog is going to open.... you  are going to see I believe 5 items in there.. well one of those items is masm.

if you look in this image.. this is the property sheet for a pl file. I am using this as an example for the moment.
But if you look you see the Item Type?? well that is a choice selection. since masm was added there is not going to be a choice added to that for masm.
![image](https://user-images.githubusercontent.com/10932297/71876111-3863de80-30e3-11ea-9790-b30ecbf50e92.png)

also since masm has been added any file that gets added or created in the project that has an extension of .asm is going to automatically met set to use the assembly compiler.

I am replicating the same process with perl... sp the addition of a .pl to the project is going to automatically set up that file to be run by perl with optional perl cli switches, and also the ability to set script switches also It is going to be more of a native interface. It is going to look like perl is apart of VS .

Now.. because we have an output file with the .asm extension. we can pass that file automatically to masm for masm to generate the object.. and since masm produces an object that is going to work it's way to the linker..

it works the same way as compiling with cl.. You do not have to tell VS to pass the object to the linker. It simply knows to do it..

everything should work in unison with no bumping of heads. because of the chain i mentioned above nothing should get out of sorts.. 

there are no extensions or addons needed to do this.. It is a matter of writing the xml files and adding the xml files to the project. If you look at that build customization dialog.. on the lower left there is a search button.. when you click that it will open a file dialog.. navigate to the xml files for the perl build customization select it. and viola there is now a check bog in the customization dialog to enable perl for that project.

![image](https://user-images.githubusercontent.com/10932297/71876694-9cd36d80-30e4-11ea-94fc-5215a1b59435.png)

I am about to start tinkering about with it again to see what I broke.
You can have a look at what VS is going and what the files need to be if you go to 

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations`

there are 2 files that make up a build custonization.. .xml, .props and .target all 3 are xml but the 3 are what create the menus and contain the rules and set the build conditions. like debug or release.

I checked and the masm build tool does not have anything special for debugging. we would have to check the compiler it's self and see if there are command line arguments for it. if there are then we copy the existing one into the project and add the bits needed to support the debugging flags.

If there are any special debugging options that can be set for the perl script when building the assembly code we can add that as well. we can have the custom build script check the input filename for x64 and if it is there and the build platform is not set to x64 then we can exclude the file from the compilation process.

This is going to make it easier when adding/changing.. delete an item.. and then add the new one.. no need to do anything else. It does all of the work. so this would make live a lot easier when migrating to 3.0 I am sure that 3.0 still uses perl but the files are not in the same locations with the same names. and that would be a hell of alot of manual entry.. It would suck! this way you  can select a group of files and add them all at the same time and presto like magic everything gets set up the way it needs to be.

**Comment by kdschlosser** [comment]
here are a few more screen shots

![image](https://user-images.githubusercontent.com/10932297/71877437-5da61c00-30e6-11ea-82e9-886c15445572.png)


![image](https://user-images.githubusercontent.com/10932297/71877471-74e50980-30e6-11ea-991b-b909b1d35dfd.png)

![image](https://user-images.githubusercontent.com/10932297/71877484-7d3d4480-30e6-11ea-8051-7197e0f91866.png)

**Comment by kiyolee** [comment]
Interesting, something I don't known much about. Will check that.

**Comment by kiyolee** [comment]
Btw, I already have openssl-3 building in similar way. I can tell that the asm stuff has not been changed much. All pl files are the same and in the same places. Except that part of the full set are compiled once more to go into libfips.

**Comment by kdschlosser** [comment]
I thought you may like that little trick that can be done with VS. Gives it a more polished look and I also think it will provide a better mechanism in terms of being able to change things easily. It add add logging ability and running conditions that are set based on the build type and platform which is a good thing as well..

It sure will make adding and removing or changing anything perl related a whole lot easier..

Now what I am thinking might be a better solution then what I had going on is to copy the current masm customization and add in the pieces needed for perl.. this way the compiler options are right there with the perl options. and we can just pass the asm right to ml without having to dink around with trying to figure how how to get it to pass the asm like what happens between cl and  link. 


I was just poking about in the VS directory.. I will say that VS, MSbuild and VC, I am sure the rest of the extensions are as well.. they made one hell of an XML whore of a program.. Holy cow.. it's like the whole program runs from XML files.

problem is that documentation on it sucks,. If you manage to locate any good information on the build customization let me know . I have not managed to locate a complete breakdown of all of the parts and pieces  to it with information on what the parts and pieces do... with decent codes examples.

See there was a guy (idk if he is an OpenSSL dev or not)

he said this
> And the files and directories change a great deal for 3.0

IDK what the deal is.. some people just want to piss in other peoples cheerios I think
¯\\\_(ツ)\_/¯ 

I personally think You have done a hell of a job putting together this set of VS solutions. While it is not able to handle all of the various build scenarios It is able to build what is commonly used. and there are tests available as well. 

I will say this.. with as complicated as the OpenSSL build system is.. I would have been amazed if what that guy said was true.. It is hard to write a build system like that.. and no one wants to modify the thing once it is working other then really small changes.. "If it ain't broke don't fix it" 

I do not understand what the purpose is for using perl to generate the assembly. All I can say is that when building using their instructions it took 20ish Minutes to compile. Using this I think it is at around 3 minutes with using multiple compiler instances.

**Comment by kiyolee** [comment]
I guess that guy was refering to new stuff. There are a lot new files in new directories. But those are fine for me. Painful ones are those relocated or renamed, I don't remember there are a lot between 1.1 and 3.0. As least those asm pl files are not relocated or renamed and they are more difficult to deal with than the c sources. I remember it was more painful between 1.0 and 1.1.

I think creating a new build system is not the main problem. As I have already figured out how things built, I can in theory recreate any build system if required. I did think about cmake, this could be a nice excercise to learn that cmake beast. Changing the workflow of openssl developers could be a bigger problem. I see that their build setup is driven by a bunch of build.info files that different developers can change independently without stuff up each other too much. For the developers, adding or removing source files are simpler and that system worked for them for a very long time. I don't see any new build system would help anything. Indeed, the build process works very well on unix type systems and I have the impression that they are more of unix developers.

Their perl asm was a surprise for me when I started digging into the sources. I guess one reason for that is the perl program can pick up common configuration data (a generated perl module) and does kind of conditional compiles.

**Comment by kdschlosser** [comment]
I have the same thoughts on them being NIX users as well. This does seem to be the case all the way downb the stack too.. the makes of curl are NIX users. and that trickles down to the makers of pyCurl. Which is where my involvement starts. I need to use pyCurl. it does not compile on windows properly. there no pre compiled binaries on pip for it..

It's funny because someone just posted this yesterday in the pyCurl issue I have up for the compilation failing.. Which has turned into a fairly long conversation.

> What is the current problem you are attempting to solve?

>    A user installing pycurl via pip install (typically does not have a compiler available, wants a precompiled binary rather than to build from source on their machine)
>    A maintainer creating release packages including binaries (needs to compile against current versions of dependencies; typically wants a reproducible process which is likely to work with new versions of compilers/dependencies; build time a secondary consideration)
>    Builds done in CI (only need to work on one system; build time is of significant importance)

My whole thing is about the speed. because of the duration of time it takes tro build OpenSSL which is needed when compiling curl, which is used to compile pyCurl those binaries cannot be made for Windows using a CI. Python has a really odd "glitch" that exists with the msvc compilers. any extensions that are compiled and any libs that extension uses MUST be compiled with the same compiler versions that was used to compile Python.. Otherwise odd behavior can ensue. 

so to cover the most commonly used versions of Python 2.7, 3.6, 3.7, 3.8 3 different msvc compilers were used.. then you need to build for x86 and x64.. that makes 6 times. If OpenSSL gets compiled using the instructions that are provided with it.. that process takes 20 minutes on my computer.. which runs at 3.5 Ghz and has 32GB of memory. a CI does is not going to have those spec. it took about 20 minutes to compile OpenSSL only a single time. there is no way a CI would build all 6 times in less then an hour.

These solutions cover most of the MSVC compilers used.. there is no solution of VS 2008 (msvc  9.0). but seeing as how Python 2.7 is the only version that uses 9.0 and is almost EOL.. meh.. it doesn't worry me so much.. I have never had an issue with compiling any extension using VS 2010 instead of 2008 when building for python 2.7 as 2008 is really not seen much anymore.

These solutions provide a mechanism that can turn a complex build problem into a single line solution. because an sln file can be processed by passing it to msbuild from the command line this makes it an ideal candidate. and if the solution has the mechanics built into it to handle perl and nasm it becomes even better. If I download the portable version of perl.. I would then need to deal with unzipping the thing using powershell or something of the like which is another step to have to deal with.. setting the environment for both nasm and perl. and it is going to take longer to download because the portable of perl is actually larger then one that can be attained by using nuget. and nuget has that cli tool which makes it easy to grab the pieces needed and to install therm into the solution...

Now I have one issue.. the folks over at pyCurl are NIX users.. they will not be able to maintain this kind of a build system.. I did not know if there was someone over at OpenSSL that would be able to.. and the answer to that is a no as well. so how do I get this thing put into place so that I am not the maintainer of it... well.. you are the one that created these things.. It would also be best if it was added to OpenSSL because that is technically where it belongs being added. Plus other projects using OpenSSL on windows would be able to benefit from it. 

If I was asked if a project of mine could be added to OpenSSL I would consider that to be a huge honer. OpenSSL is a very well known project around the globe. It is something that gets put on a resume! When you can say that you work on the OpenSSL project and that you designed the build system in VS that compiles OpenSSL It is amazing how many doors will open in terms of job advancement or being hired if working in the IT/programming field..It would have been nice if it was me :smile:, But I found my love of programming at 40 years old. to late in the game, I only knew how to program my remote control before that or my VCR (now I am really dating myself). But I have no issue with tossing out some ideas and "greasing the wheels" so to speak.... I think this build customization is the mechanism to use to make it easier to understand what is going on for this portion of the build system. 

VS has a huge amount of flexibility.. unfortunately most if it is unknown or undocumented or not very well documented. so it's a game of having to learn how to make it work.. Thankfully Microsoft has used it in VS and it is set up to do exactly what is needed. have to taylor it do make it work.. But that shouldn't be all to hard to do (so long as i don't muck it up LOL)
