### ISSUE TITLE
Add build support for ARM/ARM64 archs

### ISSUE THREAD

**Issue by triangulumlabs** [kiyolee/openssl1_1-win-build#9]
Hi,

Could you please add built support for ARM/ARM64 architectures?

**Comment by kiyolee** [comment]
Kind of on my todo list for a long time.
But I don't have an immediate use of openssl for such platforms.
So can't promise when that can be done.

**Comment by kiyolee** [comment]
Added VS2019 projects and solutions targeting ARM|ARM64.
Can't verify builds using official testsuite though.
No perl found for Windows IoT for Raspberry Pi 3 (ARM) to start with.
No access to any ARM64 hardware as well.
